---
- name: restart dnsmasq
  service:
    name: dnsmasq.service
    state: restarted

- name: update hosts
  command: /usr/local/bin/update_hosts
  notify: restart dnsmasq

- name: retart network
  service:
    name: ifup@eth0.service
    state: restarted

- name: reload iptables
  shell: /sbin/iptables-restore < /etc/iptables.ipv4.nat
  become: yes

- name: reload systemd
  command: systemctl daemon-reload
  become: yes
