---
- name: Install universal base packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - htop
      - python
      - python3
      - silversearcher-ag
      - tree
      - vim
      - zsh
